# Generated by Django 5.0.1 on 2024-01-03 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('km', models.IntegerField(blank=True, null=True)),
                ('vendido', models.BooleanField(default=False)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('foto_capa', models.ImageField(blank=True, null=True, upload_to='veiculos/')),
                ('cambio', models.CharField(choices=[('Automático', 'Automático'), ('Manual', 'Manual')], default='Manual', max_length=20)),
                ('direcao', models.CharField(choices=[('Hidráulica', 'Hidráulica'), ('Elétrica', 'Elétrica'), ('Mecânica', 'Mecânica')], default='Hidráulica', max_length=20)),
                ('acessorios', models.ManyToManyField(related_name='acessorios', to='veiculos.acessorios')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marca', to='veiculos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='veiculos/')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='veiculos.veiculo')),
            ],
        ),
    ]
