# Generated by Django 5.0.1 on 2024-01-03 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_rename_acessorios_veiculo_acessorios_veiculo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='acessorios_veiculo',
            new_name='acessorios',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='marca_veiculo',
            new_name='marca',
        ),
    ]
