# Generated by Django 5.0.1 on 2024-01-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_rename_acessorios_acessorio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acessorio',
            old_name='descricao',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='valor_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='foto_capa',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
