# Generated by Django 5.0.1 on 2026-02-23 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        (
            "veiculos",
            "0005_rename_descricao_acessorio_nome_veiculo_valor_compra_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="loja",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veiculos",
                to="accounts.loja",
            ),
        ),
    ]
