# Generated by Django 5.0.1 on 2024-01-08 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
        ('veiculos', '0005_rename_descricao_acessorio_nome_veiculo_valor_compra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manutencao',
            options={'verbose_name_plural': 'Manutenções'},
        ),
        migrations.AlterModelOptions(
            name='tipo_manutencao',
            options={'verbose_name_plural': 'Tipos de Manutenção'},
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='veiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='venda_veiculo', to='veiculos.veiculo'),
        ),
    ]
